import dateFormat from "dateformat";

function GetTime(date) {
  let hours = parseInt(dateFormat(date, "hh"));
  let minutes = parseInt(dateFormat(date, "MM"));
  let ampm = hours >= 12 ? "AM" : "PM";
  hours = hours % 12;
  hours = hours ? hours : 12; // the hour '0' should be '12'
  minutes = minutes < 10 ? "0" + minutes : minutes;
  return hours + ":" + minutes + " " + ampm;
}

const FeeReceiptPdfCode = ({
  studentName,
  studentId,
  course,
  amount,
  receiptNo,
  receiptDate,
  notes
}) => `
<!DOCTYPE html>
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
  <style>
    body {
      font-family: 'Noto Sans', sans-serif;
    }

    .receipt-container {
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
      border: 1px solid #000;
      font-size: 14px;
    }

    .header {
      text-align: center;
      font-size: 18px;
      font-weight: bold;
    }

    .receipt-section {
      margin-top: 20px;
    }

    .receipt-section-header {
      font-weight: bold;
      border-bottom: 1px solid #000;
      margin-bottom: 10px;
    }

    .receipt-table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 10px;
    }

    .receipt-table th,
    .receipt-table td {
      border: 1px solid #000;
      padding: 8px;
      text-align: left;
    }

    .footer {
      text-align: center;
      font-size: 10px;
      margin-top: 20px;
    }
  </style>
</head>

<body>
  <div class="receipt-container">
    <div class="header">
      Fee Receipt
    </div>
    <hr />

    <div class="receipt-section">
      <div class="receipt-section-header">
        Student Details:
      </div>
      <p>
        Name: ${studentName} <br />
        Student ID: ${studentId} <br />
        Course: ${course} <br />
        Date: ${receiptDate ? dateFormat(receiptDate, "dd-mm-yyyy") : dateFormat(Date.now(), "dd-mm-yyyy")} <br />
        Time: ${GetTime(new Date())}
      </p>
    </div>

    <div class="receipt-section">
      <div class="receipt-section-header">
        Receipt Details:
      </div>
      <p>
        Receipt No: ${receiptNo} <br />
        Amount: ₹ ${amount} <br />
        Notes: ${notes}
      </p>
    </div>

    <div class="footer">
      Generated by Netaji Subhas University Of Technology
    </div>
  </div>
</body>

</html>
`;

export { FeeReceiptPdfCode };
