import dateFormat from "dateformat";

function GetTime(date) {
  let hours = parseInt(dateFormat(date, "hh"));
  let minutes = parseInt(dateFormat(date, "MM"));
  let ampm = hours >= 12 ? "AM" : "PM";
  hours = hours % 12;
  hours = hours ? hours : 12; // the hour '0' should be '12'
  minutes = minutes < 10 ? "0" + minutes : minutes;
  return hours + ":" + minutes + " " + ampm;
}

const PdfCode = ({
  name,
  address,
  mobileNo,
  invoiceNo,
  lineItems,
  total,
  receivedBalance,
  paymentType,
  remainingBalance,
  tax,
  discount,
  notes
}) => `
<!DOCTYPE html>
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
  <style>
    body {
      font-family: 'Noto Sans', sans-serif;
    }

    .invoice-container {
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
      border: 1px solid #000;
      font-size: 14px;
    }

    .header {
      text-align: center;
      font-size: 18px;
      font-weight: bold;
    }

    .sub-header {
      text-align: center;
      font-size: 12px;
    }

    .invoice-section {
      margin-top: 20px;
    }

    .invoice-section-header {
      font-weight: bold;
      border-bottom: 1px solid #000;
      margin-bottom: 10px;
    }

    .invoice-table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 10px;
    }

    .invoice-table th,
    .invoice-table td {
      border: 1px solid #000;
      padding: 8px;
      text-align: left;
    }

    .footer {
      text-align: center;
      font-size: 10px;
      margin-top: 20px;
    }
  </style>
</head>

<body>
  <div class="invoice-container">
    <div class="header">
      Government of India
    </div>
    <div class="sub-header">
      e-Invoice
    </div>
    <hr />

    <div class="invoice-section">
      <div class="invoice-section-header">
        Bill To:
      </div>
      <p>
        Name: ${name} <br />
        Address: ${address} <br />
        Phone No: +91 ${mobileNo} <br />
        Date: ${dateFormat(Date.now(), "dd-mm-yyyy")} <br />
        Time: ${GetTime(new Date())}
      </p>
    </div>

    <div class="invoice-section">
      <div class="invoice-section-header">
        E-Invoice Details:
      </div>
      <p>
        Invoice No: ${invoiceNo} <br />
        Date: ${dateFormat(Date.now(), "dd-mm-yyyy")} <br />
        Time: ${GetTime(new Date())} <br />
        Mobile No: <br />
        +91 8208553219 <br />
        +91 9309780761
      </p>
    </div>

    <div class="invoice-section">
      <div class="invoice-section-header">
        Goods Details:
      </div>
      <table class="invoice-table">
        <tr>
          <th>Index</th>
          <th>Product Name</th>
          <th>Price (Per)</th>
          <th>Quantity</th>
          <th>Total</th>
        </tr>
        ${lineItems.map((item, index) => `
        <tr>
          <td>${index + 1}</td>
          <td>${item.productName}</td>
          <td>${parseFloat(item.price).toFixed(2)}</td>
          <td>${item.quantity}</td>
          <td>₹ ${parseFloat(item.quantity * item.price).toFixed(2)}</td>
        </tr>
        `).join('')}
      </table>
    </div>

    <div class="invoice-section">
      <div class="invoice-section-header">
        Summary:
      </div>
      <p>
        Subtotal: ₹ ${lineItems.reduce((acc, item) => acc + (parseFloat(item.quantity) * parseFloat(item.price)), 0).toFixed(2)} <br />
        Tax: ₹ ${tax} <br />
        Discount: ₹ ${discount} <br />
        Total: ₹ ${total} <br />
        Received Amount: ₹ ${receivedBalance} <br />
        Remaining Balance: ₹ ${remainingBalance}
      </p>
    </div>

    <div class="invoice-section">
      <div class="invoice-section-header">
        Notes:
      </div>
      <p>${notes}</p>
    </div>

    <div class="footer">
      Generated by Government of India
    </div>
  </div>
</body>

</html>
`;

export { PdfCode };
